deployment:
  tasks:
    - export DEPLOYPATH=/home/georgeel/georgeeliotarchive.org/chronology
    - npm install
    - /bin/cp -R calendar $DEPLOYPATH
    - /bin/cp -R chronology-tree $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp collection.js $DEPLOYPATH
    - cd $DEPLOYPATH && node ./collection.js