deployment:
  tasks:
    - export DEPLOYPATH=/home/georgeel/georgeeliotarchive.org/chronology
    - source ~/.nvm/nvm.sh # add nvm command
    - nvm -v
    - nvm list
    - nvm install v15
    - nvm use v15
    - npm ci
    - node collection.js
    - /bin/cp -R calendar $DEPLOYPATH
    - /bin/cp -R chronology-tree $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp collection.js $DEPLOYPATH